/* The following code was generated by JFlex 1.6.1 */

import java.lang.System;
import java.io.*;

class Yytoken {
  Yytoken
    (
     int index,
     String text,
     int line,
     int charBegin,
     int charEnd
     )
      {
	m_index = index;
	m_text = new String(text);
	m_line = line;
	m_charBegin = charBegin;
	m_charEnd = charEnd;
      }

  public int m_index;
  public String m_text;
  public int m_line;
  public int m_charBegin;
  public int m_charEnd;
  public String toString() {

String token[] = {"semicolon","eq","plus","minus","inc","dec","mod", "NOT", "less","leq","greater","geq","AND",
"OR","KeyW_Skip","KeyW_Write","KeyW_Then","KeyW_Read","KeyW_While","KeyW_Do","KeyW_If","KeyW_Else",
"Text","Text","Number","Var", "Power", "open_br", "close_br", "Comment", "Extended_Comment"};

      return token[m_index]+" : "+m_text+" (line "+m_line+", pos "
	  +m_charBegin+":"+m_charEnd+" )";
  }
}

class Application {
public static void main(String argv[]) throws java.io.IOException {
    Application app = new Application();
    String inputFile;
    if(argv.length != 0){
        inputFile = argv[0];
        if(argv.length > 1 && argv[1].equals("-filter")){
            app.print(inputFile, false);
        }else{
             app.print(inputFile, true);
        }
    }else{
        System.out.println("No arguments there.");
        inputFile = "input.txt";
        app.print(inputFile, false);
    }
    }

    void print(String inputFile, Boolean f) throws java.io.IOException{
	Lexer yy = new Lexer(new FileReader(inputFile));
	if(f == false){
	    yy.filter = false;
	}else{
	      yy.filter = true;
	}

	Yytoken t;
	do {
	try{
	    t = yy.yylex();
	    if(t == null){
        System.out.println("***Programm over***");
        break;
        }
        System.out.println(t);
	    }catch(Error e){
	        System.out.println("Unresolved symbol was found");
            break;
	    }

	} while (true);
	}
}



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>C:/Users/admin/Desktop/hw_experiment/hw_experiment/src/main/jflex/jf.jflex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\10\0\2\3\1\5\2\0\1\4\22\0\1\3\1\22\1\7\2\0"+
    "\1\21\1\25\1\0\1\12\1\13\1\11\1\17\1\0\1\20\1\0"+
    "\1\10\12\2\1\0\1\15\1\23\1\16\1\24\2\0\32\1\1\0"+
    "\1\6\2\0\1\14\1\0\1\41\2\1\1\42\1\36\1\45\1\1"+
    "\1\37\1\31\1\1\1\30\1\43\1\1\1\40\1\44\1\32\1\1"+
    "\1\34\1\27\1\35\2\1\1\33\3\1\1\0\1\26\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff93\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\0\1\12\1\13\1\14\1\0\1\15"+
    "\1\16\2\0\7\1\3\3\2\0\2\3\1\0\1\4"+
    "\1\17\1\0\1\20\1\0\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\1\1\27\5\1\1\30\2\0\2\3"+
    "\1\31\1\32\1\4\1\0\1\17\1\33\2\0\1\33"+
    "\4\0\6\1\1\0\2\33\4\0\1\34\2\1\1\35"+
    "\1\36\1\37\1\40\1\0\1\41\1\42\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\162\0\230\0\276\0\344\0\u010a"+
    "\0\u0130\0\u0156\0\u017c\0\u017c\0\u01a2\0\u017c\0\u017c\0\u017c"+
    "\0\u01c8\0\u01ee\0\u0214\0\u023a\0\u0260\0\u0286\0\u02ac\0\u02d2"+
    "\0\u02f8\0\u031e\0\u0344\0\u036a\0\u0390\0\u03b6\0\u017c\0\u03dc"+
    "\0\u0402\0\u0428\0\u044e\0\u0474\0\u049a\0\u017c\0\u04c0\0\u017c"+
    "\0\u04e6\0\u017c\0\u017c\0\u017c\0\u017c\0\u017c\0\u017c\0\u050c"+
    "\0\114\0\u0532\0\u0558\0\u057e\0\u05a4\0\u05ca\0\114\0\u05f0"+
    "\0\u0616\0\u063c\0\u0662\0\u063c\0\u05f0\0\u0688\0\u06ae\0\344"+
    "\0\u06d4\0\u06fa\0\u0720\0\u0746\0\u076c\0\u0792\0\u07b8\0\u07de"+
    "\0\u0804\0\u082a\0\u0850\0\u0876\0\u089c\0\u08c2\0\u08e8\0\u04c0"+
    "\0\u090e\0\u0934\0\u095a\0\u0980\0\u09a6\0\114\0\u09cc\0\u09f2"+
    "\0\114\0\114\0\114\0\u0980\0\u0a18\0\114\0\114\0\u07de";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\1\4\1\5\1\6\1\5\1\0\1\7"+
    "\1\10\1\11\1\12\1\13\1\0\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\3\1\27\1\3\1\30\1\31\1\32\1\33\3\3"+
    "\1\34\3\3\4\35\1\36\1\37\2\35\1\40\1\41"+
    "\1\42\1\43\32\35\1\0\2\3\11\0\1\44\12\0"+
    "\17\3\2\0\1\4\46\0\1\5\1\0\1\5\45\0"+
    "\1\37\40\0\4\7\2\0\1\45\1\46\36\7\10\0"+
    "\1\47\46\0\1\50\45\0\1\51\120\0\1\52\45\0"+
    "\1\53\45\0\1\54\45\0\1\55\54\0\1\56\46\0"+
    "\1\57\20\0\2\3\11\0\1\44\12\0\1\3\1\60"+
    "\15\3\1\0\2\3\11\0\1\44\12\0\16\3\1\61"+
    "\1\0\2\3\11\0\1\44\12\0\5\3\1\62\2\3"+
    "\1\63\6\3\1\0\2\3\11\0\1\44\12\0\7\3"+
    "\1\64\7\3\1\0\2\3\11\0\1\44\12\0\10\3"+
    "\1\65\6\3\1\0\2\3\11\0\1\44\12\0\14\3"+
    "\1\66\2\3\1\0\2\3\11\0\1\44\12\0\15\3"+
    "\1\67\1\3\5\35\1\0\2\35\1\40\1\70\2\43"+
    "\37\35\1\37\2\35\1\40\1\70\2\43\32\35\12\0"+
    "\1\71\33\0\5\72\1\0\2\72\1\0\1\73\1\72"+
    "\1\74\32\72\5\35\1\0\2\35\1\40\1\75\2\43"+
    "\37\35\1\0\3\35\1\70\2\43\32\35\1\0\1\3"+
    "\25\0\17\3\3\7\1\76\2\77\1\45\1\100\36\7"+
    "\5\101\1\0\2\101\1\102\1\103\1\101\1\104\32\101"+
    "\5\105\1\0\2\105\1\106\1\107\1\105\1\110\32\105"+
    "\1\0\2\3\11\0\1\44\12\0\2\3\1\111\14\3"+
    "\1\0\2\3\11\0\1\44\12\0\2\3\1\112\14\3"+
    "\1\0\2\3\11\0\1\44\12\0\2\3\1\113\14\3"+
    "\1\0\2\3\11\0\1\44\12\0\12\3\1\114\4\3"+
    "\1\0\2\3\11\0\1\44\12\0\7\3\1\115\7\3"+
    "\1\0\2\3\11\0\1\44\12\0\1\116\16\3\5\72"+
    "\1\0\2\72\1\0\1\73\41\72\1\0\3\72\1\0"+
    "\34\72\5\35\1\0\2\35\1\40\1\70\1\35\1\43"+
    "\37\35\1\0\2\35\1\40\1\73\1\35\1\43\32\35"+
    "\3\7\1\76\2\77\1\45\1\46\36\7\3\0\3\77"+
    "\1\7\37\0\5\101\1\0\2\101\1\102\1\103\2\104"+
    "\32\101\12\0\1\117\33\0\5\120\1\0\2\120\1\0"+
    "\1\121\34\120\5\101\1\0\3\101\1\103\2\104\32\101"+
    "\5\105\1\0\2\105\1\106\1\122\2\110\32\105\12\0"+
    "\1\123\33\0\5\124\1\0\2\124\1\0\1\125\34\124"+
    "\5\105\1\0\3\105\1\122\2\110\32\105\1\0\2\3"+
    "\11\0\1\44\12\0\3\3\1\126\13\3\1\0\2\3"+
    "\11\0\1\44\12\0\6\3\1\127\10\3\1\0\2\3"+
    "\11\0\1\44\12\0\14\3\1\130\2\3\1\0\2\3"+
    "\11\0\1\44\12\0\13\3\1\131\3\3\1\0\2\3"+
    "\11\0\1\44\12\0\11\3\1\132\5\3\1\0\2\3"+
    "\11\0\1\44\12\0\7\3\1\133\7\3\5\120\1\0"+
    "\3\120\1\0\34\120\5\101\1\0\2\101\1\102\1\121"+
    "\1\101\1\104\32\101\5\124\1\0\2\124\1\0\1\125"+
    "\1\124\1\134\37\124\1\0\3\124\1\0\34\124\5\105"+
    "\1\0\2\105\1\106\1\122\1\105\1\110\37\105\1\0"+
    "\2\105\1\106\1\135\1\105\1\110\32\105\1\0\2\3"+
    "\11\0\1\44\12\0\7\3\1\136\7\3\1\0\2\3"+
    "\11\0\1\44\12\0\7\3\1\137\7\3\5\105\1\0"+
    "\2\105\1\106\1\135\1\105\1\140\32\105";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2622];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\10\1\2\11\1\0\3\11\1\0\2\1\2\0"+
    "\11\1\1\11\2\0\2\1\1\0\1\1\1\11\1\0"+
    "\1\11\1\0\6\11\10\1\2\0\5\1\1\0\2\1"+
    "\2\0\1\1\4\0\6\1\1\0\2\1\4\0\7\1"+
    "\1\0\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  public Boolean filter;
  private int comment_count = 0;
  private int br_count = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Yytoken yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return (new Yytoken(25,yytext(),yyline,yychar,yychar+yylength()));
            }
          case 35: break;
          case 2: 
            { return (new Yytoken(24,yytext(),yyline,yychar,yychar+yylength()));
            }
          case 36: break;
          case 3: 
            { 
            }
          case 37: break;
          case 4: 
            { String str =  yytext().substring(1,yytext().length());
    return (new Yytoken(23,str,yyline,yychar,yychar + str.length()));
            }
          case 38: break;
          case 5: 
            { return (new Yytoken(5,yytext(),yyline,yychar,yychar+1));
            }
          case 39: break;
          case 6: 
            { return (new Yytoken(4,yytext(),yyline,yychar,yychar+1));
            }
          case 40: break;
          case 7: 
            { br_count++; return (new Yytoken(27,yytext(),yyline,yychar,yychar+1));
            }
          case 41: break;
          case 8: 
            { br_count--; return (new Yytoken(28,yytext(),yyline,yychar,yychar+1));
            }
          case 42: break;
          case 9: 
            { return (new Yytoken(0,yytext(),yyline,yychar,yychar+1));
            }
          case 43: break;
          case 10: 
            { return (new Yytoken(2,yytext(),yyline,yychar,yychar+1));
            }
          case 44: break;
          case 11: 
            { return (new Yytoken(3,yytext(),yyline,yychar,yychar+1));
            }
          case 45: break;
          case 12: 
            { return (new Yytoken(6,yytext(),yyline,yychar,yychar+1));
            }
          case 46: break;
          case 13: 
            { return (new Yytoken(8,yytext(),yyline,yychar,yychar+1));
            }
          case 47: break;
          case 14: 
            { return (new Yytoken(10,yytext(),yyline,yychar,yychar+1));
            }
          case 48: break;
          case 15: 
            { String str =  yytext().substring(1,yylength()-1);
    return (new Yytoken(22,str,yyline,yychar,yychar+yylength()));
            }
          case 49: break;
          case 16: 
            { return (new Yytoken(26,yytext(),yyline,yychar,yychar+2));
            }
          case 50: break;
          case 17: 
            { return (new Yytoken(1,yytext(),yyline,yychar,yychar+2));
            }
          case 51: break;
          case 18: 
            { return (new Yytoken(7,yytext(),yyline,yychar,yychar+2));
            }
          case 52: break;
          case 19: 
            { return (new Yytoken(9,yytext(),yyline,yychar,yychar+2));
            }
          case 53: break;
          case 20: 
            { return (new Yytoken(11,yytext(),yyline,yychar,yychar+2));
            }
          case 54: break;
          case 21: 
            { return (new Yytoken(12,yytext(),yyline,yychar,yychar+2));
            }
          case 55: break;
          case 22: 
            { return (new Yytoken(13,yytext(),yyline,yychar,yychar+2));
            }
          case 56: break;
          case 23: 
            { return (new Yytoken(20,yytext(),yyline,yychar,yychar+2));
            }
          case 57: break;
          case 24: 
            { return (new Yytoken(19,yytext(),yyline,yychar,yychar+2));
            }
          case 58: break;
          case 25: 
            { if (--comment_count == 0) yybegin(YYINITIAL);
            }
          case 59: break;
          case 26: 
            { comment_count++;
            }
          case 60: break;
          case 27: 
            { if(filter == false){ String str =  yytext().substring(2,yylength()-1);
                                             return (new Yytoken(29,str,yyline,yychar,yychar+yylength())); }
            }
          case 61: break;
          case 28: 
            { return (new Yytoken(14,yytext(),yyline,yychar,yychar+4));
            }
          case 62: break;
          case 29: 
            { return (new Yytoken(17,yytext(),yyline,yychar,yychar+4));
            }
          case 63: break;
          case 30: 
            { return (new Yytoken(16,yytext(),yyline,yychar,yychar+4));
            }
          case 64: break;
          case 31: 
            { return (new Yytoken(21,yytext(),yyline,yychar,yychar+4));
            }
          case 65: break;
          case 32: 
            { if(filter == false){ String str =  yytext().substring(2,yylength()-2);
                                                                   return (new Yytoken(30,str,yyline,yychar,yychar+yylength())); }
            }
          case 66: break;
          case 33: 
            { return (new Yytoken(15,yytext(),yyline,yychar,yychar+5));
            }
          case 67: break;
          case 34: 
            { return (new Yytoken(18,yytext(),yyline,yychar,yychar+5));
            }
          case 68: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
